### ISSUE TITLE
能否自定义数据存放路径？

### ISSUE THREAD

**Issue by opsarno** [eostio/Documentation#1]
默认：
```text
~/.local/share/eosio/nodeos/config
~/.local/share/eosio/nodeos/data
```
RT，需要如何修改配置，才能自定义数据存放路径呢？

**Comment by fanyang1988** [comment]
@opsarno 你是指nodeos? nodeos可以通过config.ini中的blocks-dir和data-dir指定数据路径，config路径可以通过启动参数--config-dir来指定

**Comment by fanyang1988** [comment]
@opsarno 可以参见 https://eostio.github.io/Documentation/#/zh-cn/eosforce_bios

**Comment by opsarno** [comment]
@fanyang1988 Get~ 谢谢。
